"""Presentation metadata for node properties (kept separate from the document schema)."""
from __future__ import annotations

from dataclasses import dataclass

from .core import CHOICES, LIMITS, SPECS


KNOB_KINDS = ("float_slider", "int", "bool", "enum", "xy", "xyz", "float", "color", "file_read",
              "file_write", "string", "multiline")


def _default_label(params):
    known_stems = {
        ("translate_x", "translate_y"): "Translate",
        ("center_x", "center_y"): "Center",
        ("red", "green", "blue", "alpha"): "Color",
    }
    if params in known_stems:
        return known_stems[params]
    return params[0].replace("_", " ").title()


@dataclass(frozen=True)
class KnobGroup:
    kind: str
    params: tuple[str, ...]
    label: str | None = None
    soft_range: tuple[float, float] | None = None

    def __post_init__(self):
        if self.label is None:
            object.__setattr__(self, "label", _default_label(self.params))


def _groups(*groups):
    return list(groups)


KNOB_LAYOUT = {
    "Relight": _groups(
        KnobGroup("color", ("red", "green", "blue"), label="Ambient"),
        KnobGroup("float_slider", ("diffuse",), label="Diffuse", soft_range=(0, 1)),
        KnobGroup("float_slider", ("specular",), label="Specular", soft_range=(0, 1)),
        KnobGroup("float_slider", ("mix",), label="Mix", soft_range=(0, 1)),
        KnobGroup("enum", ("use_intrinsics",), label="Use occlusion"),
        KnobGroup("float_slider", ("environment",), label="Environment", soft_range=(0, 1)),
        KnobGroup("float_slider", ("reflections",), label="Reflections", soft_range=(0, 1)),
        KnobGroup("float_slider", ("indirect",), label="Indirect", soft_range=(0, 1))),
    "ReadSplat3D": _groups(
        KnobGroup("string", ("splat_path",), label="Splat file"),
        KnobGroup("enum", ("splat_orientation",)), KnobGroup("enum", ("splat_colorspace",)),
        KnobGroup("int", ("splat_sh_degree",)),
        KnobGroup("float_slider", ("splat_relight",), label="Relight", soft_range=(0, 1)),
        KnobGroup("float_slider", ("splat_shadow_catch",), label="Catch shadows", soft_range=(0, 1)),
        KnobGroup("float_slider", ("splat_specular",), label="Keep specular", soft_range=(0, 1)),
        KnobGroup("int", ("splat_normal_smoothing",), label="Smooth normals"),
        KnobGroup("enum", ("splat_delight",), label="Delight"),
        KnobGroup("int", ("splat_delight_iterations",), label="Delight iterations"),
        KnobGroup("float_slider", ("splat_delight_smoothness",), label="Delight smoothness", soft_range=(0, 1)),
        KnobGroup("int", ("splat_delight_light_order",), label="Delight light order"),
        KnobGroup("enum", ("splat_use_intrinsics",), label="Use intrinsics"),
        KnobGroup("float_slider", ("splat_intrinsics_mix",), label="Intrinsics mix", soft_range=(0, 1)),
        KnobGroup("float_slider", ("splat_metallic",), label="Metallic", soft_range=(0, 1)),
        KnobGroup("float", ("splat_roughness",), label="Roughness"),
        KnobGroup("int", ("splat_reflection_samples",), label="Reflection samples"),
        KnobGroup("int", ("splat_indirect_samples",), label="Indirect samples"),
        KnobGroup("float", ("splat_indirect_distance",), label="Indirect distance"),
        KnobGroup("float_slider", ("splat_denoise",), label="Denoise", soft_range=(0, 1)),
        KnobGroup("enum", ("splat_quality",), label="Quality"),
        KnobGroup("enum", ("splat_cast_shadows",), label="Cast shadows"),
        KnobGroup("float", ("splat_opacity",), label="Opacity"),
        KnobGroup("float", ("splat_scale",), label="Splat scale"),
        KnobGroup("enum", ("rot_order",), label="Rotation order"),
        KnobGroup("xyz", ("tx", "ty", "tz"), label="Translate"),
        KnobGroup("xyz", ("rx", "ry", "rz"), label="Rotate"),
        KnobGroup("xyz", ("sx", "sy", "sz"), label="Scale"),
        KnobGroup("float", ("uscale",), label="Uniform scale"),
        KnobGroup("xyz", ("pivot_x", "pivot_y", "pivot_z"), label="Pivot")),
    "Read": _groups(
        KnobGroup("file_read", ("path",)), KnobGroup("enum", ("colorspace",)),
        KnobGroup("enum", ("alpha_mode",)), KnobGroup("string", ("layer",)),
        KnobGroup("int", ("subimage",)), KnobGroup("int", ("frame_offset",)),
        KnobGroup("enum", ("missing",))),
    "Constant": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("color", ("red", "green", "blue", "alpha"))),
    "Checker": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("int", ("size",))),
    "Grade": _groups(
        KnobGroup("float_slider", ("exposure",), soft_range=(-10, 10)),
        KnobGroup("float_slider", ("multiply",), soft_range=(-4, 4)),
        KnobGroup("float_slider", ("offset",), soft_range=(-10, 10)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ColorCorrect": _groups(
        KnobGroup("float_slider", ("lift",), soft_range=(-2, 2)),
        KnobGroup("float_slider", ("gamma",), soft_range=(0.1, 4)),
        KnobGroup("float_slider", ("gain",), soft_range=LIMITS["gain"]),
        KnobGroup("float_slider", ("saturation",), soft_range=LIMITS["saturation"]),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Blur": _groups(
        KnobGroup("float_slider", ("radius",), soft_range=(0, 100)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Invert": _groups(
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Clamp": _groups(
        KnobGroup("float_slider", ("minimum",), soft_range=(-1, 1)),
        KnobGroup("float_slider", ("maximum",), soft_range=(0, 4)),
        KnobGroup("bool", ("clamp_min",)), KnobGroup("bool", ("clamp_max",)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Multiply": _groups(
        KnobGroup("float_slider", ("multiply",), soft_range=(-4, 4)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Add": _groups(
        KnobGroup("float_slider", ("offset",), soft_range=(-10, 10)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Gamma": _groups(
        KnobGroup("float_slider", ("gamma",), soft_range=(0.1, 4)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Saturation": _groups(
        KnobGroup("float_slider", ("saturation",), soft_range=LIMITS["saturation"]),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Erode": _groups(
        KnobGroup("float_slider", ("erode_size",), label="Size", soft_range=(-100, 100)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Dilate": _groups(
        KnobGroup("float_slider", ("dilate_size",), label="Size", soft_range=(-100, 100)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Median": _groups(
        KnobGroup("float_slider", ("median_size",), label="Size", soft_range=(0, 20)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Sharpen": _groups(
        KnobGroup("float_slider", ("sharpen_amount",), label="Amount", soft_range=(0, 2)),
        KnobGroup("float_slider", ("sharpen_size",), label="Size", soft_range=(0, 20)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Matrix": _groups(
        KnobGroup("enum", ("matrix_size",), label="Size"),
        KnobGroup("bool", ("normalize",), label="Normalize"),
        KnobGroup("float_slider", tuple(f"weight{i}" for i in range(49)), label="Kernel", soft_range=(-10, 10)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Convolve": _groups(KnobGroup("enum", ("kernel_size",), label="Kernel size"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Laplacian": _groups(KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "EdgeDetect": _groups(KnobGroup("enum", ("edge_type",)), KnobGroup("float_slider", ("threshold",), soft_range=(0, 1)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Emboss": _groups(KnobGroup("float_slider", ("angle",), soft_range=(-180, 180)), KnobGroup("float_slider", ("width",), soft_range=(0, 20)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "BumpBoss": _groups(KnobGroup("enum", ("height_channel",)), KnobGroup("float_slider", ("light_angle",), soft_range=(-180, 180)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ErodeFilter": _groups(KnobGroup("float_slider", ("filter_size",), label="Size", soft_range=(0, 20)), KnobGroup("enum", ("filter_type",), label="Filter"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Glow": _groups(
        KnobGroup("float_slider", ("glow_threshold",), label="Threshold", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("glow_size",), label="Size", soft_range=(0, 100)),
        KnobGroup("float_slider", ("brightness",), label="Brightness", soft_range=(0, 4)),
        KnobGroup("color", ("red", "green", "blue"), label="Tint"),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Soften": _groups(
        KnobGroup("float_slider", ("soften_size",), label="Size", soft_range=(0, 100)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Defocus": _groups(
        KnobGroup("float_slider", ("defocus",), label="Defocus", soft_range=(0, 100)),
        KnobGroup("float_slider", ("aspect",), label="Aspect", soft_range=(0.25, 4)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Bilateral": _groups(KnobGroup("float_slider", ("spatial_size",), label="Spatial size", soft_range=(0, 20)), KnobGroup("float_slider", ("colour_sigma",), label="Colour sigma", soft_range=(0.001, 2)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Denoise": _groups(KnobGroup("float_slider", ("denoise_strength",), label="Strength", soft_range=(0, 2)), KnobGroup("bool", ("temporal",), label="Temporal (frame cache)"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "DegrainSimple": _groups(KnobGroup("float_slider", ("red_amount",), label="Red", soft_range=(0, 4)), KnobGroup("float_slider", ("green_amount",), label="Green", soft_range=(0, 4)), KnobGroup("float_slider", ("blue_amount",), label="Blue", soft_range=(0, 4)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ZDefocus": _groups(KnobGroup("string", ("depth_layer",), label="Depth layer"), KnobGroup("float", ("focal_plane",)), KnobGroup("float", ("depth_of_field",)), KnobGroup("float_slider", ("max_size",), label="Maximum size", soft_range=(0, 50)), KnobGroup("enum", ("depth_math",)), KnobGroup("enum", ("bokeh_shape",)), KnobGroup("int", ("blade_count",)), KnobGroup("float", ("blade_rotation",)), KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ZMerge": _groups(KnobGroup("string", ("depth_layer",), label="Depth layer"), KnobGroup("enum", ("depth_math",)), KnobGroup("float", ("smoothing",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ZSlice": _groups(KnobGroup("string", ("depth_layer",), label="Depth layer"), KnobGroup("float", ("near",)), KnobGroup("float", ("far",)), KnobGroup("float", ("falloff",)), KnobGroup("enum", ("depth_math",)), KnobGroup("enum", ("zslice_output",), label="Output"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Remove": _groups(KnobGroup("enum", ("remove_operation",), label="Operation"), KnobGroup("string", ("layers",), label="Layers")),
    "DirBlur": _groups(
        KnobGroup("enum", ("blur_type",), label="Type"),
        KnobGroup("float_slider", ("angle",), label="Angle", soft_range=(-180, 180)),
        KnobGroup("float_slider", ("length",), label="Length", soft_range=(0, 200)),
        KnobGroup("xy", ("center_x", "center_y"), label="Center"),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "DropShadow": _groups(
        KnobGroup("float_slider", ("angle",), label="Angle", soft_range=(-180, 180)),
        KnobGroup("float_slider", ("distance",), label="Distance", soft_range=(0, 100)),
        KnobGroup("float_slider", ("shadow_size",), label="Size", soft_range=(0, 100)),
        KnobGroup("float_slider", ("opacity",), label="Opacity", soft_range=(0, 1)),
        KnobGroup("color", ("red", "green", "blue"), label="Color"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "EdgeBlur": _groups(
        KnobGroup("float_slider", ("edgeblur_size",), label="Size", soft_range=(0, 100)),
        KnobGroup("float_slider", ("edge_mult",), label="Edge multiplier", soft_range=(0, 4)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "EdgeExtend": _groups(
        KnobGroup("float_slider", ("extend_size",), label="Size", soft_range=(0, 50)),
        KnobGroup("float_slider", ("extend_threshold",), label="Alpha threshold", soft_range=(0, 1)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "LightWrap": _groups(
        KnobGroup("float_slider", ("intensity",), label="Intensity", soft_range=(0, 4)),
        KnobGroup("float_slider", ("wrap_diffuse",), label="Diffuse", soft_range=(0, 100)),
        KnobGroup("float_slider", ("fgblur",), label="FG blur", soft_range=(0, 50)),
        KnobGroup("float_slider", ("bgblur",), label="BG blur", soft_range=(0, 100)),
        KnobGroup("float_slider", ("wrap_threshold",), label="Threshold", soft_range=(0, 1)),
        KnobGroup("enum", ("highlight_merge",), label="Highlight merge"),
        KnobGroup("bool", ("use_constant_highlight",), label="Use constant highlight"),
        KnobGroup("color", ("red", "green", "blue"), label="Highlight"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Dither": _groups(
        KnobGroup("int", ("bits",), label="Bits"),
        KnobGroup("float_slider", ("dither_amount",), label="Amount", soft_range=(0, 2)),
        KnobGroup("int", ("seed",), label="Seed"),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Grain": _groups(
        KnobGroup("int", ("seed",), label="Seed"),
        KnobGroup("float_slider", ("red_size",), label="Size red", soft_range=(0, 20)),
        KnobGroup("float_slider", ("green_size",), label="Size green", soft_range=(0, 20)),
        KnobGroup("float_slider", ("blue_size",), label="Size blue", soft_range=(0, 20)),
        KnobGroup("float_slider", ("red_intensity",), label="Intensity red", soft_range=(0, 1)),
        KnobGroup("float_slider", ("green_intensity",), label="Intensity green", soft_range=(0, 1)),
        KnobGroup("float_slider", ("blue_intensity",), label="Intensity blue", soft_range=(0, 1)),
        KnobGroup("bool", ("luminance_weighted",), label="Luminance weighted"),
        KnobGroup("float_slider", ("black",), label="Black", soft_range=(0, 1)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Flare": _groups(KnobGroup("xy", ("position_x", "position_y"), label="Position"), KnobGroup("string", ("tracker_id",), label="Tracker link"), KnobGroup("int", ("track_index",), label="Track index"), KnobGroup("float_slider", ("brightness",), soft_range=(0, 4)), KnobGroup("int", ("streaks",)), KnobGroup("float_slider", ("length",), soft_range=(0, 1000)), KnobGroup("float", ("rotation",)), KnobGroup("int", ("ghosts",)), KnobGroup("float", ("spread",)), KnobGroup("float_slider", ("size",), soft_range=(0, 200)), KnobGroup("color", ("red", "green", "blue")), KnobGroup("float", ("chromatic_shift",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Glint": _groups(KnobGroup("float", ("tolerance",)), KnobGroup("int", ("rays",)), KnobGroup("float", ("length",)), KnobGroup("float", ("rotation",)), KnobGroup("float", ("falloff",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Sparkles": _groups(KnobGroup("float", ("tolerance",)), KnobGroup("float", ("size",)), KnobGroup("float_slider", ("density",), soft_range=(0, 1)), KnobGroup("int", ("seed",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "GodRays": _groups(KnobGroup("xy", ("center_x", "center_y"), label="Center"), KnobGroup("int", ("steps",)), KnobGroup("float_slider", ("decay",), soft_range=(0, 1)), KnobGroup("float", ("translate",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "VolumeRays": _groups(KnobGroup("xy", ("center_x", "center_y"), label="Center"), KnobGroup("int", ("steps",)), KnobGroup("float_slider", ("decay",), soft_range=(0, 1)), KnobGroup("float", ("translate",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ScannedGrain": _groups(KnobGroup("float_slider", ("amount",), soft_range=(0, 4)), KnobGroup("float_slider", ("response",), soft_range=(0.1, 4)), KnobGroup("int", ("seed",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Posterize": _groups(
        KnobGroup("int", ("colors",), label="Colors"),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "SoftClip": _groups(
        KnobGroup("enum", ("conversion",)),
        KnobGroup("float_slider", ("softclip_min",), label="Softclip min", soft_range=(0, 1)),
        KnobGroup("float_slider", ("softclip_max",), label="Softclip max", soft_range=(0, 10)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "HSVTool": _groups(
        KnobGroup("float_slider", ("hue_range_min",), label="Hue range min", soft_range=(0, 360)),
        KnobGroup("float_slider", ("hue_range_max",), label="Hue range max", soft_range=(0, 360)),
        KnobGroup("float_slider", ("hue_rolloff",), label="Hue rolloff", soft_range=(0, 180)),
        KnobGroup("float_slider", ("hue_rotation",), label="Hue rotation", soft_range=(-180, 180)),
        KnobGroup("float_slider", ("saturation_range_min",), label="Saturation range min", soft_range=(0, 1)),
        KnobGroup("float_slider", ("saturation_range_max",), label="Saturation range max", soft_range=(0, 1)),
        KnobGroup("float_slider", ("saturation_rolloff",), label="Saturation rolloff", soft_range=(0, 1)),
        KnobGroup("float_slider", ("sat_adjust",), label="Saturation adjustment", soft_range=(-1, 2)),
        KnobGroup("bool", ("set_saturation",), label="Force saturation"),
        KnobGroup("float_slider", ("brightness_range_min",), label="Brightness range min", soft_range=(0, 1)),
        KnobGroup("float_slider", ("brightness_range_max",), label="Brightness range max", soft_range=(0, 1)),
        KnobGroup("float_slider", ("brightness_rolloff",), label="Brightness rolloff", soft_range=(0, 1)),
        KnobGroup("float_slider", ("brt_adjust",), label="Brightness adjustment", soft_range=(-1, 2)),
        KnobGroup("bool", ("set_brightness",), label="Force brightness"),
        KnobGroup("bool", ("output_alpha",), label="Output range to alpha"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "AddMix": _groups(KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Blend": _groups(
        *[KnobGroup("float", (f"weight{i}",), label=f"Weight {i}") for i in range(8)],
        KnobGroup("bool", ("normalize",)), KnobGroup("enum", ("channels",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "CopyRectangle": _groups(
        KnobGroup("enum", ("channels",)),
        KnobGroup("float", ("area_x",), label="Area left"), KnobGroup("float", ("area_y",), label="Area top"),
        KnobGroup("float", ("area_r",), label="Area right"), KnobGroup("float", ("area_t",), label="Area bottom"),
        KnobGroup("float_slider", ("softness",), soft_range=(0, 1)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Position": _groups(
        KnobGroup("int", ("translate_x",), label="Translate X"),
        KnobGroup("int", ("translate_y",), label="Translate Y")),
    "BlackOutside": _groups(),
    "AdjustBBox": _groups(
        KnobGroup("int", ("numpixels",), label="Add pixels"),
        KnobGroup("bool", ("clip_to_format",), label="Clip to format")),
    "Exposure": _groups(
        KnobGroup("enum", ("exposure_mode",), label="Adjust in"),
        KnobGroup("float_slider", ("blackpoint",), label="Black point", soft_range=(-1, 1)),
        KnobGroup("bool", ("gang",), label="Gang"),
        KnobGroup("float_slider", ("red",), label="Red", soft_range=(-5, 5)),
        KnobGroup("float_slider", ("green",), label="Green", soft_range=(-5, 5)),
        KnobGroup("float_slider", ("blue",), label="Blue", soft_range=(-5, 5)),
        KnobGroup("enum", ("channels",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "HueCorrect": _groups(
        KnobGroup("legacy", tuple(f"{prefix}_{band}" for prefix in ("sat", "lum") for band in ("red", "yellow", "green", "cyan", "blue", "magenta"))),
        *[KnobGroup("curve", (f"curve_{name}",), label=name.replace("_", " ").title()) for name in ("sat", "lum", "red", "green", "blue", "r_sup", "g_sup", "b_sup")],
        KnobGroup("float_slider", ("hue_shift",), label="Hue shift", soft_range=(-180, 180)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ColorLookup": _groups(*[KnobGroup("curve", (f"curve_{name}",), label=name.title()) for name in ("master", "red", "green", "blue", "alpha")], KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ColorMatrix": _groups(
        KnobGroup("float_slider", ("matrix_00",), label="Matrix 0,0", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_01",), label="Matrix 0,1", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_02",), label="Matrix 0,2", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_10",), label="Matrix 1,0", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_11",), label="Matrix 1,1", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_12",), label="Matrix 1,2", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_20",), label="Matrix 2,0", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_21",), label="Matrix 2,1", soft_range=(-2, 2)),
        KnobGroup("float_slider", ("matrix_22",), label="Matrix 2,2", soft_range=(-2, 2)),
        KnobGroup("bool", ("invert",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Log2Lin": _groups(KnobGroup("float", ("black",)), KnobGroup("float", ("white",)), KnobGroup("float", ("gamma",)), KnobGroup("enum", ("log_direction",), label="Direction"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "PLogLin": _groups(KnobGroup("float", ("linear_reference",), soft_range=(0.01, 1.0)), KnobGroup("float", ("log_reference",), soft_range=(-1023, 1023)), KnobGroup("float", ("density_per_code_value",), soft_range=(0.001, 0.1)), KnobGroup("float", ("negative_gamma",), soft_range=(0.1, 3.0)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "CrossTalk": _groups(*[KnobGroup("curve", (f"xt_curve_{o}_{c}",), label=f"{o.upper()} from {c.upper()}") for o in "rgb" for c in "rgb"], KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ShuffleCopy": _groups(*[KnobGroup("enum", (f"out{o}_{c}",), label=f"Out{o} {c.upper()}") for o in (1, 2) for c in "rgba"], KnobGroup("string", ("layer1",), label="In1 layer"), KnobGroup("string", ("layer2",), label="In2 layer")),
    "Toe": _groups(KnobGroup("float_slider", ("toe",), soft_range=(0, 0.99), label="Toe width"), KnobGroup("float_slider", ("toe_lift",), soft_range=(0, 0.2), label="Lift"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Expression": _groups(KnobGroup("string", ("expr_r",), label="R expression"), KnobGroup("string", ("expr_g",), label="G expression"), KnobGroup("string", ("expr_b",), label="B expression"), KnobGroup("string", ("expr_a",), label="A expression"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Vectorfield": _groups(KnobGroup("file_read", ("cube_path",), label="3D LUT (.cube, .3dl)"), KnobGroup("enum", ("interpolation",)), KnobGroup("enum", ("colorspace_in",), label="Input space"), KnobGroup("enum", ("colorspace_out",), label="Output space"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "GenerateLUT": _groups(KnobGroup("file_write", ("lut_path",), label="3D LUT (.cube)"), KnobGroup("int", ("lut_size",), label="Size"), KnobGroup("enum", ("colorspace_in",), label="Input space"), KnobGroup("enum", ("colorspace_out",), label="Output space")),
    "OCIOColorspace": _groups(KnobGroup("string", ("src",)), KnobGroup("string", ("dst",)), KnobGroup("string", ("config",)), KnobGroup("enum", ("transform_direction",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "OCIODisplay": _groups(KnobGroup("string", ("display",)), KnobGroup("string", ("view",)), KnobGroup("string", ("look",)), KnobGroup("string", ("config",)), KnobGroup("enum", ("transform_direction",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "OCIOFileTransform": _groups(KnobGroup("file_read", ("path",)), KnobGroup("enum", ("transform_direction",)), KnobGroup("enum", ("file_interpolation",)), KnobGroup("string", ("config",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "OCIOLookTransform": _groups(KnobGroup("string", ("src",)), KnobGroup("string", ("dst",)), KnobGroup("string", ("look",)), KnobGroup("string", ("config",)), KnobGroup("enum", ("transform_direction",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "OCIOLogConvert": _groups(KnobGroup("enum", ("ocio_log_operation",), label="Operation"), KnobGroup("enum", ("channels",)), KnobGroup("string", ("config",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Colorspace": _groups(KnobGroup("enum", ("primaries_in",)), KnobGroup("enum", ("primaries_out",)), KnobGroup("enum", ("transfer_in",)), KnobGroup("enum", ("transfer_out",)), KnobGroup("enum", ("whitepoint_in",)), KnobGroup("enum", ("whitepoint_out",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Tile": _groups(KnobGroup("int", ("rows",)), KnobGroup("int", ("columns",)), KnobGroup("bool", ("mirror_x",), label="Mirror alternate columns"), KnobGroup("bool", ("mirror_y",), label="Mirror alternate rows"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Histogram": _groups(KnobGroup("float", ("black",)), KnobGroup("float", ("white",)), KnobGroup("float", ("black_out",)), KnobGroup("float", ("white_out",)), KnobGroup("float", ("gamma",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "HistEQ": _groups(KnobGroup("enum", ("hist_eq_mode",), label="Equalise"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "MinColor": _groups(KnobGroup("enum", ("mincolor_mode",), label="Find"), KnobGroup("xy", ("box_x", "box_y"), label="Box origin"), KnobGroup("xy", ("box_width", "box_height"), label="Box size"), *[KnobGroup("float", (f"mincolor_{c}",), label=f"Result {c.upper()}") for c in "rgba"]),
    "Sampler": _groups(KnobGroup("xy", ("sample_x0", "sample_y0"), label="Start"), KnobGroup("xy", ("sample_x1", "sample_y1"), label="End")),
    "MatchGrade": _groups(*[KnobGroup("float", (f"grade_{axis}_{channel}",), label=f"{axis.title()} {channel.upper()}") for axis in ("lift", "gain", "gamma", "offset") for channel in "rgb"], KnobGroup("bool", ("match_analyzed",), label="Analyzed"), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Mirror": _groups(
        KnobGroup("bool", ("flip_x",), label="Flip horizontal"),
        KnobGroup("bool", ("flip_y",), label="Flip vertical"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Transform": _groups(
        KnobGroup("xy", ("translate_x", "translate_y")),
        KnobGroup("float_slider", ("rotate",), soft_range=(-180, 180)),
        KnobGroup("float_slider", ("scale",), label="Uniform scale", soft_range=(0.1, 4.0)),
        KnobGroup("enum", ("scale_mode",), label="Scale mode"),
        KnobGroup("xy", ("scale_x", "scale_y"), label="Scale"),
        KnobGroup("xy", ("center_x", "center_y"), label="Center"),
        KnobGroup("float", ("skew_x",)), KnobGroup("float", ("skew_y",)),
        KnobGroup("enum", ("skew_order",), label="Skew order"),
        KnobGroup("bool", ("invert",)), KnobGroup("bool", ("clamp",)),
        KnobGroup("bool", ("black_outside",), label="Black outside"),
        KnobGroup("bool", ("motionblur",), label="Motion blur"),
        KnobGroup("float", ("shutter",)), KnobGroup("enum", ("shutter_offset",)),
        KnobGroup("float", ("custom_offset",), label="Custom shutter offset"),
        KnobGroup("int", ("samples",)),
        KnobGroup("enum", ("filter",), label="Filter"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Crop": _groups(
        KnobGroup("int", ("x",)), KnobGroup("int", ("y",)),
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Reformat": _groups(
        KnobGroup("enum", ("reformat_type",), label="Type"),
        KnobGroup("enum", ("format",)),
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("float", ("pixel_aspect",), label="Pixel aspect"),
        KnobGroup("float_slider", ("scale",), soft_range=(0.1, 4.0)),
        KnobGroup("enum", ("resize_type",), label="Resize"),
        KnobGroup("bool", ("center",)), KnobGroup("bool", ("flip",)),
        KnobGroup("bool", ("flop",)), KnobGroup("bool", ("turn",)),
        KnobGroup("enum", ("filter",)), KnobGroup("bool", ("preserve_bbox",), label="Preserve bounding box"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "CornerPin": _groups(
        KnobGroup("xy", ("to1_x", "to1_y"), label="To 1"),
        KnobGroup("xy", ("to2_x", "to2_y"), label="To 2"),
        KnobGroup("xy", ("to3_x", "to3_y"), label="To 3"),
        KnobGroup("xy", ("to4_x", "to4_y"), label="To 4"),
        KnobGroup("xy", ("from1_x", "from1_y"), label="From 1"),
        KnobGroup("xy", ("from2_x", "from2_y"), label="From 2"),
        KnobGroup("xy", ("from3_x", "from3_y"), label="From 3"),
        KnobGroup("xy", ("from4_x", "from4_y"), label="From 4"),
        KnobGroup("enum", ("direction",)), KnobGroup("enum", ("filter",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Shuffle": _groups(
        KnobGroup("string", ("layer",)),
        KnobGroup("enum", ("red_from",)), KnobGroup("enum", ("green_from",)),
        KnobGroup("enum", ("blue_from",)), KnobGroup("enum", ("alpha_from",))),
    "STMap": _groups(
        KnobGroup("string", ("uv_layer",), label="UV layer"),
        KnobGroup("enum", ("u_channel",), label="U channel"), KnobGroup("enum", ("v_channel",), label="V channel"),
        KnobGroup("enum", ("filter",)), KnobGroup("enum", ("uv_outside",), label="Outside"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "IDistort": _groups(
        KnobGroup("string", ("uv_layer",), label="UV layer"),
        KnobGroup("enum", ("u_channel",), label="U channel"), KnobGroup("enum", ("v_channel",), label="V channel"),
        KnobGroup("xy", ("uv_scale_x", "uv_scale_y"), label="UV scale"),
        KnobGroup("xy", ("uv_offset_x", "uv_offset_y"), label="UV offset"),
        KnobGroup("enum", ("filter",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "SplineWarp": _groups(
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1)),
        KnobGroup("int", ("curve_resolution",), label="Curve resolution"),
        KnobGroup("enum", ("bbox",), label="Bounding box"),
        KnobGroup("enum", ("root_warp",), label="Root warp"),
        KnobGroup("enum", ("filter",)), KnobGroup("enum", ("output",))),
    "GridWarp": _groups(
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1)),
        KnobGroup("int", ("rows",)), KnobGroup("int", ("columns",)),
        KnobGroup("enum", ("bbox",), label="Bounding box"), KnobGroup("enum", ("filter",))),
    "VectorBlur": _groups(
        KnobGroup("string", ("uv_layer",), label="Vector layer"),
        KnobGroup("enum", ("u_channel",), label="U channel"), KnobGroup("enum", ("v_channel",), label="V channel"),
        KnobGroup("float_slider", ("vector_scale",), label="Scale", soft_range=(0, 4)),
        KnobGroup("float_slider", ("vector_offset",), label="Offset", soft_range=(-1, 1)),
        KnobGroup("enum", ("vector_method",), label="Method"),
        KnobGroup("enum", ("vector_alpha",), label="Alpha"),
        KnobGroup("float_slider", ("max_length",), label="Max length", soft_range=(0, 200)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ChannelShuffle": _groups(
        KnobGroup("enum", ("out_red",)), KnobGroup("enum", ("out_green",)),
        KnobGroup("enum", ("out_blue",)), KnobGroup("enum", ("out_alpha",))),
    "Roto": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("bool", ("invert",))),
    "Ramp": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("xy", ("p0_x", "p0_y"), label="P0"), KnobGroup("xy", ("p1_x", "p1_y"), label="P1"),
        KnobGroup("color", ("color0_red", "color0_green", "color0_blue", "color0_alpha"), label="Colour 0"),
        KnobGroup("color", ("color1_red", "color1_green", "color1_blue", "color1_alpha"), label="Colour 1"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Radial": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("xy", ("box_x", "box_y"), label="Area"),
        KnobGroup("xy", ("box_width", "box_height"), label="Area size"),
        KnobGroup("float_slider", ("softness",), soft_range=(0, 1)),
        KnobGroup("color", ("red", "green", "blue", "alpha")),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Rectangle": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("xy", ("box_x", "box_y"), label="Area"),
        KnobGroup("xy", ("box_width", "box_height"), label="Area size"),
        KnobGroup("float_slider", ("softness",), soft_range=(0, 1)),
        KnobGroup("color", ("red", "green", "blue", "alpha")),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Noise": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("float_slider", ("size",), soft_range=(2, 512)),
        KnobGroup("float_slider", ("z_slice",), soft_range=(-10, 10)),
        KnobGroup("int", ("octaves",)), KnobGroup("float_slider", ("lacunarity",), soft_range=(1, 4)),
        KnobGroup("float_slider", ("gain",), soft_range=(0, 1)),
        KnobGroup("float_slider", ("gamma",), soft_range=(0.1, 4)),
        KnobGroup("int", ("seed",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Text": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("multiline", ("message",)), KnobGroup("string", ("font",)),
        KnobGroup("float_slider", ("font_size",), soft_range=(4, 300)),
        KnobGroup("xy", ("box_x", "box_y"), label="Box"),
        KnobGroup("xy", ("box_width", "box_height"), label="Box size"),
        KnobGroup("enum", ("justify",)),
        KnobGroup("color", ("red", "green", "blue", "alpha")),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Tracker": _groups(
        KnobGroup("int", ("reference_frame",)), KnobGroup("enum", ("mode",)),
        KnobGroup("bool", ("apply_translate",)), KnobGroup("bool", ("apply_rotate",)),
        KnobGroup("bool", ("apply_scale",)), KnobGroup("int", ("smoothing",)),
        KnobGroup("int", ("pattern_radius",)), KnobGroup("int", ("search_radius",)),
        KnobGroup("bool", ("adaptive_update",)), KnobGroup("enum", ("tracking_channels",)),
        KnobGroup("enum", ("filter",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Stabilize": _groups(
        KnobGroup("int", ("reference_frame",)), KnobGroup("bool", ("apply_translate",)),
        KnobGroup("bool", ("apply_rotate",)), KnobGroup("bool", ("apply_scale",)),
        KnobGroup("int", ("smoothing",)), KnobGroup("int", ("pattern_radius",)),
        KnobGroup("int", ("search_radius",)), KnobGroup("bool", ("adaptive_update",)),
        KnobGroup("enum", ("tracking_channels",)), KnobGroup("enum", ("filter",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Merge": _groups(
        KnobGroup("enum", ("operation",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Dissolve": _groups(
        KnobGroup("float_slider", ("which",), soft_range=(0, 1)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "TimeDissolve": _groups(KnobGroup("int", ("in",)), KnobGroup("int", ("out",)),
        KnobGroup("enum", ("ease",)), KnobGroup("float_slider", ("which",), soft_range=(0, 1)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "TimeBlur": _groups(KnobGroup("float", ("shutter",)), KnobGroup("int", ("divisions",)),
        KnobGroup("enum", ("shutter_offset",)), KnobGroup("float", ("custom_offset",))),
    "TimeEcho": _groups(KnobGroup("int", ("frames",)), KnobGroup("enum", ("method",)),
        KnobGroup("float_slider", ("falloff",), soft_range=(0, 1))),
    "MotionBlur2D": _groups(KnobGroup("float", ("shutter",)), KnobGroup("enum", ("shutter_offset",)),
        KnobGroup("float", ("custom_offset",)), KnobGroup("int", ("samples",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "MotionBlur3D": _groups(KnobGroup("float", ("shutter",)), KnobGroup("enum", ("shutter_offset",)),
        KnobGroup("float", ("custom_offset",)), KnobGroup("int", ("samples",)), KnobGroup("float", ("mix",))),
    "VectorGenerator": _groups(KnobGroup("int", ("vector_detail",)), KnobGroup("float", ("smoothness",)), KnobGroup("enum", ("flow_on",)), KnobGroup("enum", ("flow_backend",))),
    "Kronos": _groups(KnobGroup("float", ("speed",)), KnobGroup("float", ("frame",)), KnobGroup("enum", ("interpolation",)), KnobGroup("int", ("shutter_samples",)), KnobGroup("enum", ("flow_backend",))),
    "MotionBlur": _groups(KnobGroup("float", ("shutter",)), KnobGroup("enum", ("shutter_offset",)), KnobGroup("float", ("custom_offset",)), KnobGroup("int", ("samples",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1)), KnobGroup("enum", ("flow_backend",))),
    "SmartVector": _groups(KnobGroup("int", ("reference_frame",)), KnobGroup("int", ("frame_start",)),
        KnobGroup("int", ("frame_end",)), KnobGroup("int", ("vector_detail",)),
        KnobGroup("float", ("smoothness",)), KnobGroup("int", ("reanchor_interval",))),
    "VectorDistort": _groups(KnobGroup("int", ("reference_frame",)), KnobGroup("float", ("blur_size",)),
        KnobGroup("int", ("fade_frames",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "VectorCornerPin": _groups(KnobGroup("int", ("reference_frame",)),
        KnobGroup("xy", ("corner1_x", "corner1_y"), label="Top left"),
        KnobGroup("xy", ("corner2_x", "corner2_y"), label="Top right"),
        KnobGroup("xy", ("corner3_x", "corner3_y"), label="Bottom right"),
        KnobGroup("xy", ("corner4_x", "corner4_y"), label="Bottom left"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Inpaint": _groups(KnobGroup("int", ("temporal_frames",)), KnobGroup("enum", ("fill_method",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "CurveTool": _groups(KnobGroup("int", ("frame_start",)), KnobGroup("int", ("frame_end",)),
        KnobGroup("xy", ("box_x", "box_y")), KnobGroup("xy", ("box_width", "box_height")),
        *[KnobGroup("float", (f"average_{c}",), label=f"Average {c.upper()}") for c in "rgba"],
        KnobGroup("float", ("average_luminance",), label="Average luminance"),
        KnobGroup("xy", ("crop_x", "crop_y")), KnobGroup("xy", ("crop_width", "crop_height")),
        KnobGroup("xy", ("max_x", "max_y")), KnobGroup("float", ("max_value",), label="Maximum luminance pixel value"),
        KnobGroup("xy", ("min_x", "min_y")), KnobGroup("float", ("min_value",), label="Minimum luminance pixel value"),
        KnobGroup("float", ("exposure_diff",), label="Exposure difference")),
    "ContactSheet": _groups(KnobGroup("int", ("rows",)), KnobGroup("int", ("columns",)),
        KnobGroup("int", ("gap",)), KnobGroup("enum", ("labels",)), KnobGroup("enum", ("fit",)),
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",))),
    "Keymix": _groups(
        KnobGroup("bool", ("invert_mask",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Copy": _groups(
        KnobGroup("enum", ("copy_red",)), KnobGroup("enum", ("copy_green",)),
        KnobGroup("enum", ("copy_blue",)), KnobGroup("enum", ("copy_alpha",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ChannelMerge": _groups(
        KnobGroup("enum", ("a_channel",)), KnobGroup("enum", ("b_channel",)),
        KnobGroup("enum", ("operation",)), KnobGroup("enum", ("out_channel",)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Keyer": _groups(
        KnobGroup("enum", ("keyer_operation",), label="Operation"),
        KnobGroup("float_slider", ("range_a",), label="A", soft_range=(0, 1)),
        KnobGroup("float_slider", ("range_b",), label="B", soft_range=(0, 1)),
        KnobGroup("float_slider", ("range_c",), label="C", soft_range=(0, 1)),
        KnobGroup("float_slider", ("range_d",), label="D", soft_range=(0, 1)),
        KnobGroup("bool", ("invert",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "HueKeyer": _groups(
        KnobGroup("float_slider", ("hue_center",), label="Hue center", soft_range=(0, 360)),
        KnobGroup("float_slider", ("hue_width",), label="Hue width", soft_range=(0, 360)),
        KnobGroup("float_slider", ("hue_softness",), label="Hue softness", soft_range=(0, 180)),
        KnobGroup("float_slider", ("sat_min",), label="Saturation min", soft_range=(0, 1)),
        KnobGroup("float_slider", ("sat_max",), label="Saturation max", soft_range=(0, 1)),
        KnobGroup("bool", ("invert",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ChromaKeyer": _groups(
        KnobGroup("color", ("key_red", "key_green", "key_blue"), label="Key colour"),
        KnobGroup("float_slider", ("key_tolerance",), label="Tolerance", soft_range=(0, 1)),
        KnobGroup("float_slider", ("key_softness",), label="Softness", soft_range=(0, 1)),
        KnobGroup("float_slider", ("luma_gain",), label="Luminance gain", soft_range=(0, 2)),
        KnobGroup("float_slider", ("shadow_level",), label="Shadow level", soft_range=(0, 0.2)),
        KnobGroup("float_slider", ("highlight_level",), label="Highlight level", soft_range=(0, 10)),
        KnobGroup("bool", ("despill",), label="Despill"),
        KnobGroup("float_slider", ("despill_bias",), label="Despill bias", soft_range=(0, 1)),
        KnobGroup("bool", ("premultiply",), label="Premultiply"),
        KnobGroup("bool", ("invert",)), KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "ScreenKeyer": _groups(
        KnobGroup("color", ("screen_red", "screen_green", "screen_blue"), label="Screen colour"),
        KnobGroup("float_slider", ("screen_gain",), label="Screen gain", soft_range=(0, 4)),
        KnobGroup("float_slider", ("screen_balance",), label="Screen balance", soft_range=(0, 1)),
        KnobGroup("float_slider", ("despill_bias",), label="Despill bias", soft_range=(0, 1)),
        KnobGroup("float_slider", ("alpha_bias",), label="Alpha bias", soft_range=(-1, 1)),
        KnobGroup("float_slider", ("clip_black",), label="Clip black", soft_range=(0, 1)),
        KnobGroup("float_slider", ("clip_white",), label="Clip white", soft_range=(0, 1)),
        KnobGroup("float_slider", ("clip_rollback",), label="Clip rollback", soft_range=(0, 1)),
        KnobGroup("float_slider", ("screen_shrink",), label="Screen shrink/grow", soft_range=(-10, 10)),
        KnobGroup("float_slider", ("screen_softness",), label="Screen softness", soft_range=(0, 10)),
        KnobGroup("enum", ("keyer_view",), label="View"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Cryptomatte": _groups(
        KnobGroup("string", ("crypto_layer",), label="Layer"),
        KnobGroup("string", ("matte_list",), label="Matte list"),
        KnobGroup("enum", ("crypto_view",), label="View"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "IBKColor": _groups(
        KnobGroup("enum", ("screen_type",), label="Screen type"),
        KnobGroup("int", ("fill_size",), label="Size"),
        KnobGroup("float_slider", ("screen_erode",), label="Erode", soft_range=(0, 10)),
        KnobGroup("float_slider", ("darks",), label="Darks", soft_range=(0, 1)),
        KnobGroup("float_slider", ("lights",), label="Lights", soft_range=(0, 10)),
        KnobGroup("bool", ("patch_black",), label="Patch black"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "IBKGizmo": _groups(
        KnobGroup("enum", ("screen_type",), label="Screen type"),
        KnobGroup("float_slider", ("red_weight",), label="Red weight", soft_range=(0, 1)),
        KnobGroup("float_slider", ("blue_green_weight",), label="Blue/green weight", soft_range=(0, 1)),
        KnobGroup("bool", ("luminance_match",), label="Luminance match"),
        KnobGroup("float_slider", ("luminance_level",), label="Luminance level", soft_range=(0, 1)),
        KnobGroup("bool", ("use_bg_luminance",), label="Use BG luminance"),
        KnobGroup("bool", ("screen_subtraction",), label="Screen subtraction"),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "Difference": _groups(
        KnobGroup("float_slider", ("offset",), soft_range=(-1, 1)),
        KnobGroup("float_slider", ("gain",), soft_range=(0, 4)),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "TimeOffset": _groups(
        KnobGroup("int", ("time_offset",)), KnobGroup("bool", ("reverse",))),
    "FrameHold": _groups(
        KnobGroup("int", ("first_frame",)), KnobGroup("int", ("increment",))),
    "Retime": _groups(
        KnobGroup("int", ("input_range_start",), label="Input range start"),
        KnobGroup("int", ("input_range_end",), label="Input range end"),
        KnobGroup("int", ("output_range_start",), label="Output range start"),
        KnobGroup("int", ("output_range_end",), label="Output range end"),
        KnobGroup("float_slider", ("speed",), soft_range=(-4.0, 4.0))),
    "TimeClip": _groups(
        KnobGroup("enum", ("frame_range_type",), label="Frame range type"),
        KnobGroup("int", ("first",)), KnobGroup("int", ("last",)),
        KnobGroup("enum", ("before",)), KnobGroup("enum", ("after",)),
        KnobGroup("int", ("time_offset",))),
    "FrameRange": _groups(
        KnobGroup("int", ("first_frame",)), KnobGroup("int", ("last_frame",)),
        KnobGroup("enum", ("before",)), KnobGroup("enum", ("after",))),
    "AppendClip": _groups(
        KnobGroup("int", ("first_frame",)), KnobGroup("int", ("dissolve",)),
        *(KnobGroup("int", (f"length{i}",), label=f"Length {i}") for i in range(8))),
    "Grid": _groups(
        KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
        KnobGroup("xy", ("spacing_x", "spacing_y"), label="Spacing"),
        KnobGroup("int", ("number_x",), label="Lines in X"), KnobGroup("int", ("number_y",), label="Lines in Y"),
        KnobGroup("xy", ("grid_offset_x", "grid_offset_y"), label="Offset"),
        KnobGroup("float", ("line_width",)),
        KnobGroup("color", ("red", "green", "blue", "alpha")),
        KnobGroup("float_slider", ("mix",), soft_range=(0, 1))),
    "NoOp": _groups(KnobGroup("multiline", ("note",))),
    "PostageStamp": _groups(KnobGroup("bool", ("hide_input",), label="Hide input")),
    "ViewMetaData": [], "CompareMetaData": [],
    "ModifyMetaData": _groups(KnobGroup("multiline", ("edits",), label="Edits")),
    "CopyMetaData": _groups(KnobGroup("string", ("keys",), label="Keys")),
    "AddTimeCode": _groups(KnobGroup("string", ("timecode",), label="Start timecode"),
                           KnobGroup("float", ("fps",), label="FPS"), KnobGroup("int", ("start_frame",)),
                           KnobGroup("bool", ("drop_frame",), label="Drop frame")),
    "BurnIn": _groups(
        KnobGroup("string", ("top_left",)), KnobGroup("string", ("top_right",)),
        KnobGroup("string", ("bottom_left",)), KnobGroup("string", ("bottom_right",)),
        KnobGroup("string", ("center",), label="Centre"), KnobGroup("string", ("font",)),
        KnobGroup("float_slider", ("font_size",), soft_range=(4, 200)),
        KnobGroup("float_slider", ("margin",), soft_range=(0, 100)),
        KnobGroup("color", ("red", "green", "blue", "alpha")),
        KnobGroup("bool", ("bar",), label="Background bar"),
        KnobGroup("float_slider", ("bar_opacity",), label="Bar opacity", soft_range=(0, 1))),
    "Backdrop": _groups(KnobGroup("color", ("red", "green", "blue")),
                        KnobGroup("xy", ("width", "height"), label="Size")),
    "Group": [], "Output": [],
    "Input": _groups(KnobGroup("int", ("input_number",), label="Number")),
    "Premult": [], "Unpremult": [], "Dot": [],
    "Switch": _groups(KnobGroup("int", ("which",))),
    "Viewer": [],
    "Write": _groups(
        KnobGroup("file_write", ("path",)), KnobGroup("enum", ("file_type",)),
        KnobGroup("enum", ("bit_depth",)), KnobGroup("bool", ("bundle",), label="Conditioning bundle")),
    "ReadBundle": _groups(
        KnobGroup("string", ("path",), label="Model output"),
        KnobGroup("string", ("bundle",), label="Bundle manifest"),
        KnobGroup("enum", ("colorspace",)), KnobGroup("enum", ("alpha_mode",))),
}

# 3D panels follow Nuke: a vector is one row of typed fields, a size or a distance is a typed
# field, and a slider appears only where the value is a bounded scalar that is natural to scrub
# (an angle, a 0..1 amount, an intensity).
# Every node that carries a transform shows the same block in Nuke's order: rotation order,
# translate, rotate, scale, uniform scale, pivot.
_TRANSLATE_KNOB = KnobGroup("xyz", ("tx", "ty", "tz"), label="Translate")
_XFORM_KNOBS = (KnobGroup("enum", ("rot_order",), label="Rotation order"),
                _TRANSLATE_KNOB,
                KnobGroup("xyz", ("rx", "ry", "rz"), label="Rotate"),
                KnobGroup("xyz", ("sx", "sy", "sz"), label="Scale"),
                KnobGroup("float", ("uscale",), label="Uniform scale"),
                KnobGroup("xyz", ("pivot_x", "pivot_y", "pivot_z"), label="Pivot"))
_FORCE_KNOBS = (KnobGroup("float", ("probability",), label="Probability"),
                KnobGroup("int", ("from_frame",), label="From frame"),
                KnobGroup("int", ("to_frame",), label="To frame"),
                KnobGroup("int", ("seed",), label="Random seed"))
_SURFACE_KNOB = KnobGroup("color", ("red", "green", "blue", "alpha"))
# Specular amount is a 0..1 mix and scrubs well. Shininess and emission are open-ended magnitudes:
# a slider across their whole legal range put all the useful values in its first few pixels.
_LIQUID_KNOBS = (KnobGroup("enum", ("material",), label="Material"),
                 KnobGroup("float", ("ior",), label="IOR"),
                 KnobGroup("color", ("absorption_red", "absorption_green", "absorption_blue"), label="Absorption color"),
                 KnobGroup("float", ("absorption_distance",), label="Absorption distance"),
                 KnobGroup("float", ("reflection",), label="Reflection"),
                 KnobGroup("float", ("roughness",), label="Roughness"))
_MATERIAL_KNOBS = (KnobGroup("float_slider", ("spec_amount",), label="Specular", soft_range=LIMITS["spec_amount"]),
                   KnobGroup("float", ("spec_shininess",), label="Shininess"),
                   KnobGroup("float", ("emission",), label="Emission"),
                   # Physically based material (materials 1, R1): read only when `material` is "pbr"
                   # (the `spec_amount`/`spec_shininess` knobs above stay what "standard" reads).
                   KnobGroup("float_slider", ("metallic",), label="Metallic", soft_range=LIMITS["metallic"]),
                   KnobGroup("float_slider", ("pbr_roughness",), label="Roughness (PBR)", soft_range=LIMITS["pbr_roughness"]),
                   KnobGroup("float_slider", ("pbr_specular",), label="Specular (PBR)", soft_range=LIMITS["pbr_specular"]),
                   *_LIQUID_KNOBS)
_TARGET_KNOB = KnobGroup("xyz", ("target_x", "target_y", "target_z"), label="Look at")
# Nuke's own knob names for polygon amount, shared by Card3D, Sphere3D and Cylinder3D.
_ROWS_COLUMNS_KNOBS = (KnobGroup("int", ("rows",)), KnobGroup("int", ("columns",)))
KNOB_LAYOUT.update({
    "Card3D": _groups(KnobGroup("float", ("card_width",), label="Width"),
                      KnobGroup("float", ("card_height",), label="Height"),
                      *_ROWS_COLUMNS_KNOBS, *_XFORM_KNOBS, _SURFACE_KNOB, *_MATERIAL_KNOBS),
    "Cube3D": _groups(KnobGroup("float", ("cube_size",), label="Size"),
                      *_XFORM_KNOBS, _SURFACE_KNOB, *_MATERIAL_KNOBS),
    "Sphere3D": _groups(KnobGroup("float", ("sphere_radius",), label="Radius"),
                        KnobGroup("int", ("segments",), label="Segments (legacy)"),
                        *_ROWS_COLUMNS_KNOBS, *_XFORM_KNOBS, _SURFACE_KNOB, *_MATERIAL_KNOBS),
    "Cylinder3D": _groups(KnobGroup("float", ("cyl_radius",), label="Radius"),
                          KnobGroup("float", ("cyl_height",), label="Height"),
                          *_ROWS_COLUMNS_KNOBS, KnobGroup("enum", ("cyl_caps",), label="Caps"),
                          *_XFORM_KNOBS, _SURFACE_KNOB, *_MATERIAL_KNOBS),
    "ReadAlembic3D": _groups(KnobGroup("string", ("abc_path",), label="Alembic file"),
                             KnobGroup("string", ("abc_root",), label="Root object")),
    "ReadAlembicCamera3D": _groups(KnobGroup("string", ("abc_path",), label="Alembic file"),
                                   KnobGroup("string", ("abc_camera",), label="Camera object")),
    "ReadUSD3D": _groups(KnobGroup("string", ("usd_path",), label="USD file"),
                         KnobGroup("string", ("usd_root",), label="Root prim")),
    "ReadUSDCamera3D": _groups(KnobGroup("string", ("usd_path",), label="USD file"),
                               KnobGroup("string", ("usd_camera",), label="Camera prim")),
    "ReadGLTF3D": _groups(KnobGroup("string", ("gltf_path",), label="glTF file"),
                          KnobGroup("string", ("gltf_root",), label="Root node")),
    "ReadGeo3D": _groups(KnobGroup("string", ("geo_path",), label="OBJ file"), *_XFORM_KNOBS, _SURFACE_KNOB, *_MATERIAL_KNOBS),
    "Light3D": _groups(KnobGroup("enum", ("light_type",), label="Type"),
                       KnobGroup("enum", ("shadows",), label="Shadows"),
                       KnobGroup("float", ("shadow_bias",), label="Shadow bias"),
                       KnobGroup("float", ("shadow_blur",), label="Shadow blur"),
                       KnobGroup("int", ("shadow_samples",), label="Shadow samples"),
                       KnobGroup("float", ("env_rotation",), label="Environment rotation"),
                       KnobGroup("float", ("env_blur",), label="Environment blur"),
                       _TRANSLATE_KNOB, _TARGET_KNOB,
                       KnobGroup("enum", ("falloff_type",), label="Falloff"),
                       KnobGroup("float", ("cone_angle",), label="Cone angle"),
                       KnobGroup("float", ("cone_penumbra_angle",), label="Cone penumbra angle"),
                       KnobGroup("float", ("cone_falloff",), label="Cone falloff"),
                       # Rect/Disc/Sphere (R2): a real-size emitter, read only for those types.
                       KnobGroup("float", ("area_width",), label="Width (Rect)"),
                       KnobGroup("float", ("area_height",), label="Height (Rect)"),
                       KnobGroup("float", ("area_radius",), label="Radius (Disc/Sphere)"),
                       KnobGroup("enum", ("area_normalize",), label="Normalize"),
                       KnobGroup("enum", ("two_sided",), label="Two-sided (Rect/Disc)"),
                       KnobGroup("int", ("light_samples",), label="Light samples"),
                       KnobGroup("float", ("exposure",), label="Exposure (stops)"),
                       KnobGroup("enum", ("light_color_mode",), label="Color mode"),
                       KnobGroup("float", ("kelvin",), label="Color temperature (K)"),
                       KnobGroup("color", ("red", "green", "blue"), label="Color"),
                       KnobGroup("float_slider", ("intensity",), soft_range=(0, 5))),
    "Camera3D": _groups(_TRANSLATE_KNOB, _TARGET_KNOB,
                        KnobGroup("float_slider", ("roll",), soft_range=(-180, 180)),
                        KnobGroup("float", ("focal",), label="Focal length (mm)"),
                        KnobGroup("float", ("haperture",), label="Horizontal aperture (mm)"),
                        KnobGroup("float", ("vaperture",), label="Vertical aperture (mm)"),
                        KnobGroup("float", ("near",)), KnobGroup("float", ("far",)),
                        KnobGroup("float", ("fstop",), label="F-stop (0 = pinhole)"),
                        KnobGroup("float", ("focus_distance",), label="Focus distance"),
                        KnobGroup("int", ("aperture_blades",), label="Aperture blades (0 = round)"),
                        KnobGroup("float", ("blade_rotation",), label="Blade rotation (degrees)"),
                        KnobGroup("float", ("anamorphic_squeeze",), label="Anamorphic squeeze")),
    "Project3D": _groups(KnobGroup("enum", ("project_outside",), label="Outside"),
                         KnobGroup("enum", ("project_backfaces",), label="Backfaces"),
                         KnobGroup("enum", ("project_occlusion",), label="Occlusion")),
    "WriteGeo3D": _groups(KnobGroup("string", ("geo_write_path",), label="OBJ / USD file")),
    "WriteSplat3D": _groups(KnobGroup("string", ("splat_write_path",), label="Splat file"),
                            KnobGroup("int", ("splat_write_overwrite",), label="Overwrite")),
    "WriteVDB3D": _groups(KnobGroup("string", ("vdb_write_path",), label="VDB file or sequence"),
                          KnobGroup("int", ("vdb_write_overwrite",), label="Overwrite"),
                          KnobGroup("enum", ("vdb_write_compression",), label="Compression"),
                          KnobGroup("int", ("vdb_write_half",), label="Half float"),
                          KnobGroup("float", ("vdb_write_narrow_band",), label="Narrow band (voxels)")),
    "Scene3D": _groups(*_XFORM_KNOBS),
    "Axis3D": _groups(*_XFORM_KNOBS),
    "TransformGeo3D": _groups(*_XFORM_KNOBS),
    "MergeGeo3D": _groups(*_XFORM_KNOBS),
    "Normals3D": _groups(KnobGroup("enum", ("normals_mode",), label="Mode"),
                         KnobGroup("bool", ("flip_winding",), label="Flip winding")),
    "DisplaceGeo3D": _groups(KnobGroup("float", ("displace_scale",), label="Scale"),
                             KnobGroup("float", ("displace_offset",), label="Offset"),
                             KnobGroup("enum", ("displace_channel",), label="Channel"),
                             KnobGroup("bool", ("recompute_normals",), label="Recompute normals")),
    "Shrinkwrap3D": _groups(KnobGroup("enum", ("wrap_shape",), label="Proxy shape"),
                           KnobGroup("int", ("wrap_resolution",), label="Resolution"),
                           KnobGroup("enum", ("wrap_mode",), label="Mode"),
                           KnobGroup("float", ("wrap_offset",), label="Offset"),
                           KnobGroup("int", ("wrap_smooth_iterations",), label="Smooth iterations"),
                           KnobGroup("float_slider", ("wrap_falloff",), label="Falloff", soft_range=(0, 1))),
    "Instance3D": _groups(
        KnobGroup("float", ("inst_scale",), label="Scale"),
        KnobGroup("float_slider", ("inst_scale_random",), label="Scale random", soft_range=(0, 1)),
        KnobGroup("enum", ("inst_orient",), label="Orient"),
        KnobGroup("float_slider", ("inst_rotate_random",), label="Rotate random", soft_range=(0, 180)),
        KnobGroup("float", ("inst_spin",), label="Spin (per frame of age)"),
        KnobGroup("enum", ("inst_variant",), label="Variant"),
        KnobGroup("bool", ("inst_color_from_points",), label="Color from points"),
        KnobGroup("int", ("seed",), label="Random seed")),
    "ParticleEmitter3D": _groups(
        KnobGroup("enum", ("emit_from",), label="Emit from"),
        KnobGroup("float", ("emit_rate",), label="Emission rate"),
        KnobGroup("enum", ("emit_rate_unit",), label="Rate unit"),
        KnobGroup("int", ("start_frame",), label="Start at"),
        KnobGroup("float", ("life",), label="Lifetime (frames)"),
        KnobGroup("float", ("life_variance",), label="Lifetime variation"),
        KnobGroup("float", ("emit_speed",), label="Speed"),
        KnobGroup("float", ("speed_variance",), label="Speed variation"),
        KnobGroup("xyz", ("emit_dir_x", "emit_dir_y", "emit_dir_z"), label="Direction"),
        KnobGroup("bool", ("direction_from_normals",), label="Direction from normals"),
        KnobGroup("float", ("spread",), label="Spread (degrees)"),
        KnobGroup("float", ("particle_size",), label="Size"),
        KnobGroup("float", ("size_variance",), label="Size variation"),
        KnobGroup("color", ("red", "green", "blue", "alpha"), label="Color"),
        KnobGroup("int", ("seed",), label="Random seed"),
        KnobGroup("int", ("substeps",), label="Substeps"),
        KnobGroup("int", ("max_particles",), label="Maximum particles"),
        KnobGroup("bool", ("animated",), label="Animated geometry"),
        KnobGroup("float", ("inherit_velocity",), label="Inherit velocity"),
        *_XFORM_KNOBS),
    "ParticleGravity3D": _groups(
        KnobGroup("xyz", ("gravity_x", "gravity_y", "gravity_z"), label="Direction"),
        KnobGroup("float", ("strength",), label="Strength"), *_FORCE_KNOBS),
    "ParticleDrag3D": _groups(
        KnobGroup("float", ("drag",), label="Drag"),
        KnobGroup("float", ("drag_quadratic",), label="Quadratic drag"), *_FORCE_KNOBS),
    "ParticleWind3D": _groups(
        KnobGroup("xyz", ("wind_x", "wind_y", "wind_z"), label="Direction"),
        KnobGroup("float", ("strength",), label="Strength"),
        KnobGroup("float", ("wind_gust",), label="Gust"),
        KnobGroup("float", ("wind_gust_rate",), label="Gust rate (cycles per frame)"), *_FORCE_KNOBS),
    "ParticleTurbulence3D": _groups(
        KnobGroup("enum", ("turb_mode",), label="Field"),
        KnobGroup("float", ("turb_size",), label="Size"),
        KnobGroup("float", ("strength",), label="Strength"),
        KnobGroup("int", ("octaves",), label="Octaves"), *_FORCE_KNOBS),
    "ParticleBounce3D": _groups(
        KnobGroup("float", ("bounce",), label="Bounce"),
        KnobGroup("float", ("friction",), label="Friction"),
        KnobGroup("bool", ("kill_on_collision",), label="Kill on collision"),
        KnobGroup("bool", ("animated",), label="Animated geometry"), *_FORCE_KNOBS),
    "ParticleCollide3D": _groups(
        KnobGroup("float", ("collide_radius",), label="Radius"),
        KnobGroup("bool", ("radius_from_size",), label="Radius from size"),
        KnobGroup("int", ("iterations",), label="Iterations"),
        KnobGroup("float", ("restitution",), label="Restitution"),
        KnobGroup("float", ("friction",), label="Friction"),
        KnobGroup("float", ("sleep_threshold",), label="Sleep threshold"), *_FORCE_KNOBS),
    "ParticleRender3D": _groups(
        KnobGroup("enum", ("representation",), label="Representation"),
        KnobGroup("float", ("size_scale",), label="Size scale"),
        KnobGroup("float", ("foam_density",), label="Foam density"),
        KnobGroup("float", ("spray_size",), label="Spray size"),
        KnobGroup("enum", ("particle_material",), label="Material"),
        KnobGroup("float_slider", ("particle_metallic",), label="Metallic", soft_range=(0, 1)),
        KnobGroup("float_slider", ("particle_pbr_roughness",), label="Roughness", soft_range=(0, 1)),
        KnobGroup("float_slider", ("particle_pbr_specular",), label="Specular", soft_range=(0, 1)),
        KnobGroup("float", ("particle_emission",), label="Emission"),
        KnobGroup("bool", ("particle_cast_shadows",), label="Cast shadows"),
        KnobGroup("enum", ("particle_ramp_by",), label="Ramp by"),
        KnobGroup("string", ("particle_color_ramp",), label="Colour ramp"),
        KnobGroup("string", ("particle_opacity_ramp",), label="Opacity ramp"),
        KnobGroup("string", ("particle_size_ramp",), label="Size ramp"),
        KnobGroup("string", ("particle_emission_ramp",), label="Emission ramp")),
    "ReadVDB3D": _groups(KnobGroup("string", ("vdb_path",), label="VDB file or sequence"),
                         KnobGroup("string", ("density_grid",), label="Density grid"),
                         KnobGroup("string", ("temperature_grid",), label="Temperature grid"),
                         KnobGroup("string", ("velocity_grid",), label="Velocity grid"),
                         KnobGroup("int", ("frame_offset",), label="Frame offset"),
                         KnobGroup("float", ("voxel_scale",), label="Voxel scale"), *_XFORM_KNOBS),
    "FluidSource3D": _groups(
        KnobGroup("enum", ("fluid_emit_from",), label="Emit from"),
        KnobGroup("xyz", ("src_center_x", "src_center_y", "src_center_z"), label="Center"),
        KnobGroup("float", ("src_radius",), label="Radius"),
        KnobGroup("float", ("src_falloff",), label="Falloff"),
        KnobGroup("float", ("src_density",), label="Density"),
        KnobGroup("float", ("src_temperature",), label="Temperature"),
        KnobGroup("float", ("src_fuel",), label="Fuel"),
        KnobGroup("xyz", ("src_vel_x", "src_vel_y", "src_vel_z"), label="Velocity"),
        KnobGroup("float", ("src_inherit_velocity",), label="Inherit velocity"),
        KnobGroup("float", ("src_noise_amount",), label="Noise amount"),
        KnobGroup("float", ("src_noise_scale",), label="Noise scale"),
        KnobGroup("int", ("start_frame",), label="Start at"),
        KnobGroup("int", ("end_frame",), label="End at"),
        KnobGroup("enum", ("fluid_type",), label="Fluid type"), *_XFORM_KNOBS),
    "FluidForce3D": _groups(
        KnobGroup("enum", ("force_kind",), label="Kind"),
        KnobGroup("float", ("buoyancy_lift",), label="Buoyancy lift"),
        KnobGroup("float", ("buoyancy_settle",), label="Density settling"),
        KnobGroup("float", ("ambient_temperature",), label="Ambient temperature"),
        KnobGroup("xyz", ("force_dir_x", "force_dir_y", "force_dir_z"), label="Direction"),
        KnobGroup("float", ("strength",), label="Strength"),
        KnobGroup("float", ("turbulence_scale",), label="Turbulence scale"),
        KnobGroup("float", ("turbulence_speed",), label="Turbulence speed"),
        KnobGroup("float", ("drag",), label="Drag"),
        KnobGroup("int", ("from_frame",), label="From frame"), KnobGroup("int", ("to_frame",), label="To frame"),
        KnobGroup("int", ("seed",), label="Random seed")),
    "FluidCollide3D": _groups(KnobGroup("bool", ("animated",), label="Animated geometry")),
    "FluidSolver3D": _groups(
        KnobGroup("float", ("division_size",), label="Division size"),
        KnobGroup("xyz", ("bounds_min_x", "bounds_min_y", "bounds_min_z"), label="Bounds min"),
        KnobGroup("xyz", ("bounds_max_x", "bounds_max_y", "bounds_max_z"), label="Bounds max"),
        KnobGroup("int", ("start_frame",), label="Start at"), KnobGroup("int", ("substeps",), label="Substeps"),
        KnobGroup("int", ("seed",), label="Random seed"), KnobGroup("enum", ("advection",), label="Advection"),
        KnobGroup("float", ("vorticity",), label="Vorticity"), KnobGroup("float", ("dissipation",), label="Dissipation"),
        KnobGroup("float", ("cooling_rate",), label="Cooling rate"),
        KnobGroup("enum", ("boundary_x",), label="Boundary X"), KnobGroup("enum", ("boundary_y",), label="Boundary Y"),
        KnobGroup("enum", ("boundary_z",), label="Boundary Z"),
        KnobGroup("float", ("tolerance",), label="Tolerance"), KnobGroup("int", ("max_iterations",), label="Maximum iterations"),
        KnobGroup("enum", ("pressure",), label="Pressure solver"),
        KnobGroup("bool", ("fire",), label="Fire"), KnobGroup("float", ("ignition_temperature",), label="Ignition temperature"),
        KnobGroup("float", ("burn_rate",), label="Burn rate"), KnobGroup("float", ("flame_lifespan",), label="Flame lifespan"),
        KnobGroup("float", ("fuel_inefficiency",), label="Fuel inefficiency"),
        KnobGroup("float", ("temperature_output",), label="Temperature output"),
        KnobGroup("float", ("smoke_output",), label="Smoke output"),
        KnobGroup("float", ("gas_release",), label="Gas release"),
        KnobGroup("float", ("burn_heat",), label="Legacy heat output"),
        KnobGroup("float", ("burn_smoke",), label="Legacy smoke output"),
        KnobGroup("float", ("burn_expansion",), label="Legacy expansion"),
        # Shape tab (Houdini Pyro vocabulary): disturbance, shredding, turbulence and the shared control-field
        # remap, which also gates dissipation.
        KnobGroup("enum", ("dissipation_field",), label="Dissipation field"),
        KnobGroup("float", ("dissipation_range_lo",), label="Dissipation range low"),
        KnobGroup("float", ("dissipation_range_hi",), label="Dissipation range high"),
        KnobGroup("float", ("dissipation_ramp",), label="Dissipation ramp"),
        KnobGroup("float", ("disturbance",), label="Disturbance"),
        KnobGroup("float", ("disturbance_size",), label="Disturbance block size"),
        KnobGroup("enum", ("disturbance_field",), label="Disturbance field"),
        KnobGroup("float", ("disturbance_range_lo",), label="Disturbance range low"),
        KnobGroup("float", ("disturbance_range_hi",), label="Disturbance range high"),
        KnobGroup("float", ("disturbance_ramp",), label="Disturbance ramp"),
        KnobGroup("float", ("shredding",), label="Shredding"),
        KnobGroup("float", ("turbulence",), label="Turbulence"),
        KnobGroup("float", ("swirl_size",), label="Swirl size"),
        KnobGroup("int", ("grain",), label="Grain"),
        KnobGroup("float", ("pulse_length",), label="Pulse length"),
        KnobGroup("enum", ("turbulence_field",), label="Turbulence field"),
        KnobGroup("float", ("turbulence_range_lo",), label="Turbulence range low"),
        KnobGroup("float", ("turbulence_range_hi",), label="Turbulence range high"),
        KnobGroup("float", ("turbulence_ramp",), label="Turbulence ramp")),
    "FluidLiquidSolver3D": _groups(
        KnobGroup("float", ("division_size",), label="Division size"),
        KnobGroup("xyz", ("bounds_min_x", "bounds_min_y", "bounds_min_z"), label="Bounds min"),
        KnobGroup("xyz", ("bounds_max_x", "bounds_max_y", "bounds_max_z"), label="Bounds max"),
        KnobGroup("int", ("start_frame",), label="Start at"), KnobGroup("int", ("substeps",), label="Substeps"),
        KnobGroup("int", ("seed",), label="Random seed"),
        KnobGroup("float", ("flip_ratio",), label="FLIP ratio"),
        KnobGroup("int", ("particles_per_cell",), label="Particles per cell"),
        KnobGroup("float", ("liquid_gravity",), label="Gravity"), KnobGroup("float", ("viscosity",), label="Viscosity"),
        KnobGroup("enum", ("viscosity_by_attribute",), label="Viscosity attribute"),
        KnobGroup("float", ("narrow_band",), label="Narrow band (cells)"),
        KnobGroup("float", ("tolerance",), label="Tolerance"), KnobGroup("int", ("max_iterations",), label="Maximum iterations"),
        KnobGroup("enum", ("pressure",), label="Pressure solver"),
        KnobGroup("bool", ("liquid_sdf",), label="Signed distance output")),
    "FluidSurface3D": _groups(KnobGroup("float", ("particle_radius",), label="Particle radius"),
                              KnobGroup("int", ("smoothing",), label="Smoothing"),
                              KnobGroup("int", ("surface_resolution",), label="Resolution"),
                              KnobGroup("int", ("detail_ratio",), label="Detail ratio"),
                              KnobGroup("int", ("temporal_smoothing",), label="Temporal smoothing (frames)"),
                              KnobGroup("bool", ("thin_sheet_preservation",), label="Preserve thin sheets"), *_LIQUID_KNOBS),
    "FluidFoam3D": _groups(KnobGroup("float", ("foam_speed",), label="Speed threshold"),
                           KnobGroup("float", ("foam_curvature",), label="Curvature threshold"),
                           KnobGroup("float", ("foam_size",), label="Size")),
    "FluidWhitewater3D": _groups(
        KnobGroup("float", ("foam_emission", "spray_emission", "bubbles_emission"), label="Emission rates"),
        KnobGroup("float", ("foam_threshold", "spray_threshold", "bubbles_threshold"), label="Emission thresholds"),
        KnobGroup("float", ("trapped_air_min", "trapped_air_max"), label="Trapped-air potential range"),
        KnobGroup("float", ("wave_crest_min", "wave_crest_max"), label="Wave-crest potential range"),
        KnobGroup("float", ("kinetic_energy_min", "kinetic_energy_max"), label="Kinetic-energy potential range"),
        KnobGroup("float", ("foam_lifespan", "particle_lifespan"), label="Lifespans"),
        KnobGroup("int", ("max_particles",), label="Particle cap"),
        KnobGroup("float", ("foam_size", "spray_size", "bubbles_size"), label="Particle sizes"),
        KnobGroup("float", ("surface_band", "surface_offset", "spray_lift"), label="Surface"),
        KnobGroup("float", ("gravity", "spray_drag", "bubble_buoyancy", "bubble_drag"), label="Motion"),
        KnobGroup("int", ("seed",), label="Random seed"),
        KnobGroup("int", ("cache_memory_mb", "cache_disk_mb"), label="Cache budgets (MB)")),
    "FluidCache3D": _groups(KnobGroup("int", ("cache_memory_mb",), label="Memory budget (MB)"),
                            KnobGroup("int", ("cache_disk_mb",), label="Disk budget (MB)"),
                            KnobGroup("enum", ("cache_precision",), label="Precision"),
                            KnobGroup("enum", ("cache_channels",), label="Channels")),
    "FluidUpres3D": _groups(KnobGroup("enum", ("upres_factor",), label="Up-res factor"),
                            KnobGroup("enum", ("upres_backend",), label="Backend"),
                            KnobGroup("float", ("turbulence",), label="Turbulence"),
                            KnobGroup("float", ("swirl_size",), label="Swirl size"),
                            KnobGroup("int", ("grain",), label="Grain"),
                            KnobGroup("float", ("pulse_length",), label="Pulse length"),
                            KnobGroup("float", ("shredding",), label="Shredding"),
                            KnobGroup("int", ("seed",), label="Random seed"),
                            KnobGroup("int", ("cache_memory_mb",), label="Memory budget (MB)"),
                            KnobGroup("int", ("cache_disk_mb",), label="Disk budget (MB)")),
    "Plume3D": _groups(KnobGroup("int", ("plume_resolution",), label="Resolution"),
                       KnobGroup("int", ("plume_seed",), label="Random seed"), *_XFORM_KNOBS),
    "ParticleCache3D": _groups(KnobGroup("int", ("cache_memory_mb",), label="Memory budget (MB)"),
                               KnobGroup("int", ("cache_disk_mb",), label="Disk budget (MB)")),
    "Render3D": _groups(KnobGroup("int", ("width",)), KnobGroup("int", ("height",)),
                        KnobGroup("color", ("red", "green", "blue", "alpha"), label="Background"),
                        KnobGroup("float_slider", ("ambient",), soft_range=(0, 1)),
                        KnobGroup("int", ("samples",), label="Antialiasing samples"),
                        KnobGroup("enum", ("render_output",), label="Output"),
                        KnobGroup("string", ("passes",), label="Passes (multichannel)"),
                        KnobGroup("enum", ("render_backend",), label="Backend"),
                        KnobGroup("enum", ("render_mode",), label="Mode"),
                        KnobGroup("int", ("pt_samples",), label="Path samples"),
                        KnobGroup("int", ("max_bounces",), label="Max bounces"),
                        KnobGroup("int", ("diffuse_bounces",), label="Diffuse bounces"),
                        KnobGroup("int", ("specular_bounces",), label="Specular bounces"),
                        KnobGroup("int", ("transmission_bounces",), label="Transmission bounces"),
                        KnobGroup("float", ("time_limit",), label="Time limit (s)"),
                        KnobGroup("float", ("noise_threshold",), label="Noise threshold"),
                        KnobGroup("int", ("pt_seed",), label="Path seed"),
                        KnobGroup("bool", ("cryptomatte",), label="Cryptomatte"),
                        KnobGroup("int", ("cryptomatte_levels",), label="Cryptomatte levels")),
})


def _inverted_binary_name(param):
    return param in {"invert", "apply_translate", "apply_rotate", "apply_scale"}


def _scalar_kind(node_type, param, value=None):
    if param in CHOICES:
        return "enum"
    if param == "path" and node_type == "Read":
        return "file_read"
    if param == "path" and node_type == "Write":
        return "file_write"
    if isinstance(value, str):
        return "string"
    if _inverted_binary_name(param):
        return "bool"
    if param in {"which", "subimage"}:
        return "int"
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "bool" if LIMITS.get(param) == (0, 1) else "int"
    return "float_slider"


def _fallback_layout(node_type):
    return [KnobGroup(_scalar_kind(node_type, param, default), (param,))
            for param, default in SPECS[node_type]["params"].items()]


def knob_layout(node_type):
    """Return presentation groups, deriving simple groups for newly added node types."""
    return KNOB_LAYOUT.get(node_type, _fallback_layout(node_type))


def resolve_kind(node_type, param, value):
    """Resolve one parameter to the kind used by its node's presentation layout."""
    for group in knob_layout(node_type):
        if param in group.params:
            return group.kind
    return _scalar_kind(node_type, param, value)

# Render3D's volume knobs, with Houdini Pyro's names (docs/FLUIDS_SPIKE.md).
KNOB_LAYOUT["Render3D"] += [
    KnobGroup("enum", ("volumes",), label="Volumes"),
    KnobGroup("float", ("volume_step_size",), label="Volume step size"),
    KnobGroup("float", ("volume_density_scale",), label="Density scale"),
    KnobGroup("float", ("volume_shadow_density",), label="Shadow density"),
    KnobGroup("int", ("volume_shadow_steps",), label="Shadow steps"),
    KnobGroup("float", ("volume_scattering",), label="Scattering"),
    KnobGroup("float", ("volume_absorption",), label="Absorption"),
    KnobGroup("color", ("volume_red", "volume_green", "volume_blue"), label="Smoke color"),
    KnobGroup("float", ("volume_fps",), label="Frame rate (motion vectors)"),
    KnobGroup("float", ("volume_depth_threshold",), label="Depth threshold"),
    KnobGroup("int", ("motion_blur",), label="Motion blur (geometry, camera)"),
    KnobGroup("float", ("shutter",), label="Shutter (frames)"),
    KnobGroup("enum", ("shutter_offset",), label="Shutter offset"),
    KnobGroup("float", ("custom_offset",), label="Custom shutter offset"),
    KnobGroup("int", ("motion_samples",), label="Motion samples"),
    KnobGroup("float", ("volume_motion_blur",), label="Motion blur (frames)"),
    KnobGroup("int", ("volume_motion_samples",), label="Motion blur samples"),
    KnobGroup("enum", ("volume_quality",), label="Volume quality"),
    KnobGroup("float", ("volume_anisotropy",), label="Anisotropy"),
    KnobGroup("float", ("volume_multi_scatter",), label="Multiple scattering"),
    KnobGroup("float", ("volume_multi_scatter_blur",), label="Multiple scattering blur"),
    KnobGroup("float", ("volume_fire_intensity",), label="Fire intensity"),
    KnobGroup("float", ("volume_temperature_scale",), label="Temperature scale (K)"),
    KnobGroup("float", ("volume_fire_threshold",), label="Fire threshold (K)"),
    KnobGroup("float", ("volume_fire_light",), label="Fire light on smoke"),
    KnobGroup("string", ("volume_fire_ramp",), label="Fire color ramp")]
