"""Image metadata: string keys to string values that ride with a raster (`Raster.meta`).

Key names follow Nuke: `input/filename`, `input/frame`, `input/width`, `input/height` (filled by Read),
`exr/<name>` for an OpenEXR header attribute, `timecode`, and any `a/b` key another tool wrote. A raster whose
`meta` is None has no metadata. Dicts held by a raster are never edited in place: every function here returns
a new dict, so a cached raster can be shared by any number of readers.

Substitution (`expand`) is the one expression language the metadata nodes and BurnIn share: `[frame]` is the
timeline frame, `[metadata key]` the value of a key (empty when the key is absent).
"""
from __future__ import annotations

import re

# OpenEXR header entries that describe the file's layout. The writer derives them from the pixels, so they
# are neither listed as metadata on read nor written back from it.
STRUCTURAL_ATTRIBUTES = frozenset({
    "compression", "PixelAspectRatio", "screenWindowCenter", "screenWindowWidth", "DateTime",
    "colorInteropID", "Orientation", "chunkCount", "type", "name", "view", "dataWindow", "displayWindow",
    "lineOrder", "channels",
})

TIMECODE_KEY = "timecode"
EXR_TIMECODE_ATTRIBUTE = "smpte:TimeCode"   # OpenEXR's own timecode attribute: two uint32 words, not a string

_SUBSTITUTION = re.compile(r"\[\s*(frame|metadata)(?:\s+([^\]]*?))?\s*\]")


def header_entry(name, value):
    """`(key, string value)` for an EXR header attribute, or None when it is not metadata."""
    if name == EXR_TIMECODE_ATTRIBUTE:
        try:
            return TIMECODE_KEY, words_to_timecode(value[0])
        except (TypeError, IndexError, ValueError):
            return None
    if name in STRUCTURAL_ATTRIBUTES or ":" in name:
        return None
    return (name if "/" in name else "exr/" + name), str(value)


def key_to_header(key):
    """The EXR header attribute a metadata key is written as, or None when it is not a plain string
    attribute (`input/...` describes where the pixels came from and is regenerated by the next Read; the
    timecode is written as the typed attribute by `timecode_words`)."""
    if key.startswith("input/") or key == TIMECODE_KEY:
        return None
    name = key[4:] if key.startswith("exr/") else key
    return None if not name or name in STRUCTURAL_ATTRIBUTES or ":" in name else name


def header_metadata(meta):
    """`{header attribute: value}` for the keys of `meta` that a file header holds as strings."""
    out = {}
    for key, value in (meta or {}).items():
        header = key_to_header(key)
        if header is not None:
            out[header] = str(value)
    return out


def timecode_words(meta):
    """The `smpte:TimeCode` attribute value `(time word, user word)` for the `timecode` key, or None."""
    text = (meta or {}).get(TIMECODE_KEY)
    if text is None:
        return None
    try:
        return timecode_to_words(text), 0
    except ValueError:
        return None


def expand(text, meta, frame):
    """Replace `[frame]` and `[metadata key]` in `text`."""
    if "[" not in text:
        return text

    def one(match):
        if match.group(1) == "frame":
            return str(int(frame))
        return str((meta or {}).get((match.group(2) or "").strip(), ""))
    return _SUBSTITUTION.sub(one, text)


def uses_frame(text):
    return any(m.group(1) == "frame" for m in _SUBSTITUTION.finditer(text))


# --- ModifyMetaData -------------------------------------------------------------------------------

def parse_edits(text):
    """Parse the edit list: one edit per line, `set <key> <value>`, `remove <key>` or `rename <old> <new>`.

    Blank lines and lines starting with `#` are skipped. Raises ValueError naming the bad line.
    """
    edits = []
    for number, raw in enumerate(str(text).splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 2)
        verb = parts[0].lower()
        if verb == "set" and len(parts) >= 2:
            edits.append(("set", parts[1], parts[2] if len(parts) > 2 else ""))
        elif verb == "remove" and len(parts) == 2:
            edits.append(("remove", parts[1], None))
        elif verb == "rename" and len(parts) == 3 and " " not in parts[2].strip():
            edits.append(("rename", parts[1], parts[2].strip()))
        else:
            raise ValueError(f"line {number}: expected 'set <key> <value>', 'remove <key>' or "
                             f"'rename <old> <new>', got {raw.strip()!r}")
    return edits


def modify(meta, edits_text, frame):
    """`meta` after the edits, applied in order. A value may hold `[frame]` and `[metadata key]`."""
    out = dict(meta or {})
    for verb, key, value in parse_edits(edits_text):
        if verb == "set":
            out[key] = expand(value, out, frame)
        elif verb == "remove":
            out.pop(key, None)
        elif key in out:
            out[value] = out.pop(key)
    return out or None


# --- CopyMetaData / CompareMetaData ----------------------------------------------------------------

def key_list(text):
    return [k for k in re.split(r"[,\s]+", str(text)) if k]


def copy(target, source, keys_text=""):
    """`target` with the listed keys of `source` (all keys when the list is empty) laid over it."""
    keys = key_list(keys_text)
    out = dict(target or {})
    for key, value in (source or {}).items():
        if not keys or key in keys:
            out[key] = value
    return out or None


def compare(a, b):
    """`[(key, value in a or None, value in b or None)]` for every key whose value differs, sorted by key."""
    a, b = a or {}, b or {}
    return [(key, a.get(key), b.get(key)) for key in sorted(set(a) | set(b)) if a.get(key) != b.get(key)]


# --- AddTimeCode -----------------------------------------------------------------------------------

_TIMECODE = re.compile(r"^\s*(\d{1,2})[:;](\d{2})[:;](\d{2})[:;.](\d{2,3})\s*$")


def _nominal_fps(fps):
    return int(round(float(fps)))


def _drop_frames(fps):
    """Frames dropped per minute for a drop-frame rate: 2 at 29.97, 4 at 59.94, else 0."""
    nominal = _nominal_fps(fps)
    if nominal in (30, 60) and abs(float(fps) - nominal * 1000.0 / 1001.0) < 0.01:
        return nominal // 15
    return 0


def timecode_to_frames(text, fps, drop_frame=False):
    """The frame count a timecode string stands for."""
    match = _TIMECODE.match(str(text))
    if not match:
        raise ValueError(f"timecode {text!r} is not HH:MM:SS:FF")
    hours, minutes, seconds, frames = (int(g) for g in match.groups())
    nominal = _nominal_fps(fps)
    if frames >= nominal:
        raise ValueError(f"timecode {text!r} has frame {frames}, but {fps} fps has {nominal} frames a second")
    total = ((hours * 60 + minutes) * 60 + seconds) * nominal + frames
    drop = _drop_frames(fps) if drop_frame else 0
    if drop:
        total_minutes = hours * 60 + minutes
        total -= drop * (total_minutes - total_minutes // 10)
    return total


def frames_to_timecode(frames, fps, drop_frame=False):
    """The `HH:MM:SS:FF` string for a frame count (`;` before the frames in drop-frame)."""
    frames = max(0, int(frames))
    nominal = _nominal_fps(fps)
    drop = _drop_frames(fps) if drop_frame else 0
    if drop:
        per_ten = nominal * 600 - drop * 9
        tens, rest = divmod(frames, per_ten)
        if rest > drop:
            frames += drop * 9 * tens + drop * ((rest - drop) // (nominal * 60 - drop))
        else:
            frames += drop * 9 * tens
    seconds, ff = divmod(frames, nominal)
    minutes, ss = divmod(seconds, 60)
    hours, mm = divmod(minutes, 60)
    return f"{hours % 24:02d}:{mm:02d}:{ss:02d}{';' if drop else ':'}{ff:02d}"


def timecode_at(start, fps, start_frame, frame, drop_frame=False):
    """The timecode shown at timeline `frame` when `start` is shown at `start_frame`."""
    base = timecode_to_frames(start, fps, drop_frame)
    return frames_to_timecode(base + int(frame) - int(start_frame), fps, drop_frame)


def timecode_to_words(text):
    """SMPTE 12M time word (BCD digits, drop-frame flag at bit 6) for an `HH:MM:SS:FF` string."""
    match = _TIMECODE.match(str(text))
    if not match:
        raise ValueError(f"timecode {text!r} is not HH:MM:SS:FF")
    h, m, s, f = (int(g) for g in match.groups())
    drop = ";" in str(text)
    return ((f % 10) | (f // 10) << 4 | int(drop) << 6 | (s % 10) << 8 | (s // 10) << 12
            | (m % 10) << 16 | (m // 10) << 20 | (h % 10) << 24 | (h // 10) << 28)


def words_to_timecode(word):
    word = int(word)
    digit = lambda shift, bits: (word >> shift) & ((1 << bits) - 1)   # noqa: E731
    sep = ";" if word >> 6 & 1 else ":"
    return (f"{digit(28, 2) * 10 + digit(24, 4):02d}:{digit(20, 3) * 10 + digit(16, 4):02d}:"
            f"{digit(12, 3) * 10 + digit(8, 4):02d}{sep}{digit(4, 2) * 10 + digit(0, 4):02d}")
