"""Rebuild examples/mixed_scene: a small 3D project with opaque geometry, a transparent pane, a splat cloud, a camera
and a light, rendered by one Render3D into beauty, depth, position and object_id layers and written as one EXR.

The splat cloud is generated here from a fixed seed (a spiral of soft discs), so `cloud.ply` can be regenerated byte for
byte instead of being treated as a capture. Run it from the repository root:

    python tools/make_mixed_scene_example.py            # writes examples/mixed_scene/{cloud.ply,mixed_scene.nbcomp}
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nodebased import splats                        # noqa: E402
from nodebased.core import Dispatcher, atomic_save  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[1] / "examples" / "mixed_scene"
SPLAT_COUNT = 4000
SEED = 7
PASSES = "beauty,depth,position,object_id"


def spiral_cloud(count=SPLAT_COUNT, seed=SEED):
    """A two-armed spiral of soft, slightly flattened discs in warm and cool colours, about 3.4 units across."""
    rng = np.random.default_rng(seed)
    t = rng.uniform(0.0, 1.0, count)
    arm = rng.integers(0, 2, count)
    angle = t * 5.5 + arm * np.pi
    radius = 0.25 + 1.45 * t
    jitter = rng.normal(0.0, 0.07, (count, 3))
    centres = np.column_stack((radius * np.cos(angle), radius * np.sin(angle) * 0.75 + 0.35,
                               -0.7 + 1.1 * (t - 0.5) + rng.normal(0.0, 0.12, count))) + jitter
    scales = np.column_stack((rng.uniform(0.05, 0.13, count), rng.uniform(0.05, 0.13, count),
                              rng.uniform(0.012, 0.03, count)))
    quats = rng.normal(size=(count, 4))
    quats /= np.linalg.norm(quats, axis=1, keepdims=True)
    warm = np.array([1.0, 0.55, 0.2])
    cool = np.array([0.25, 0.6, 1.0])
    mix = np.where(arm[:, None] == 0, warm, cool) * (0.55 + 0.45 * rng.uniform(size=(count, 1)))
    sh = ((mix - 0.5) / splats.C0)[:, None, :]
    opacity = rng.uniform(0.35, 0.9, count)
    return splats.SplatCloud(centres, scales, quats, opacity, sh, 0, colorspace="linear")


def build_document():
    d = Dispatcher()
    # (id, type, name, position, params): sources in a column on the left, the scene and camera in the middle, the render
    # and the Write on the right
    nodes = (
        ("cloud", "ReadSplat3D", "Splat cloud", (-480, -330), dict(splat_path="cloud.ply", splat_colorspace="linear")),
        ("backdrop", "Card3D", "Opaque backdrop", (-480, -230),
         dict(card_width=9.0, card_height=6.0, tz=-3.0, red=0.18, green=0.2, blue=0.26)),
        ("cube", "Cube3D", "Opaque cube", (-480, -130),
         dict(cube_size=1.3, tx=-1.7, ty=-0.55, tz=0.1, ry=28.0, red=0.9, green=0.35, blue=0.25)),
        ("ball", "Sphere3D", "Opaque sphere", (-480, -30),
         dict(sphere_radius=0.75, tx=1.5, ty=-0.8, tz=-0.2, red=0.35, green=0.85, blue=0.45)),
        ("glass", "Card3D", "Transparent pane", (-480, 70),
         dict(card_width=2.0, card_height=2.4, tx=0.6, ty=-0.2, tz=1.1, red=0.5, green=0.75, blue=1.0, alpha=0.35)),
        ("key", "Light3D", "Key light", (-480, 170), dict(tx=2.5, ty=4.0, tz=4.0, intensity=1.1)),
        ("camera", "Camera3D", "Camera", (-200, 170), dict(tx=0.0, ty=0.4, tz=7.0, target_y=0.0)),
        ("scene", "Scene3D", "Scene", (-200, -90), {}),
        ("render", "Render3D", "Render: beauty, depth, position, object_id", (80, -90),
         dict(width=640, height=360, samples=1, ambient=0.25, render_output="multichannel", passes=PASSES,
              render_backend="auto", render_mode="raster")),
        ("write", "Write", "Write layered EXR", (80, 40), dict(bit_depth="float", file_type="exr")),
    )
    for key, kind, name, pos, params in nodes:
        d.execute({"op": "create", "id": key, "type": kind, "name": name, "pos": list(pos), "params": params})
    for slot, source in (("object0", "cloud"), ("object1", "backdrop"), ("object2", "cube"), ("object3", "ball"),
                         ("object4", "glass"), ("object5", "key")):
        d.execute({"op": "connect", "id": "scene", "input": slot, "source": source})
    d.execute({"op": "connect", "id": "render", "input": "scene", "source": "scene"})
    d.execute({"op": "connect", "id": "render", "input": "camera", "source": "camera"})
    d.execute({"op": "connect", "id": "write", "input": "image", "source": "render"})
    d.execute({"op": "view", "id": "render"})
    return d.document


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    ply = OUTPUT / "cloud.ply"
    splats.write_ply(spiral_cloud(), str(ply))
    document = build_document()
    document["nodes"]["cloud"]["params"]["splat_path"] = str(ply)
    atomic_save(OUTPUT / "mixed_scene.nbcomp", document)
    print(f"wrote {ply} ({ply.stat().st_size} bytes) and {OUTPUT / 'mixed_scene.nbcomp'}")


if __name__ == "__main__":
    main()
